### ISSUE TITLE
parsing the output file and generating raw QA pairs

### ISSUE THREAD

**Issue by gililior** [julianmichael/qasrl-modeling#1]
Hey @julianmichael,
After running the pretrained model with the 
command
```
python qasrl/pipelines/afirst_pipeline_sequential.py \
  --span models/span_density_softmax.tar.gz \
  --span_to_question models/span_to_question.tar.gz \
  --span_min_prob 0.02 \
  --question_min_prob 0.01 \
  --question_beam_size 20 \
  --input_file data/qasrl-dev-mini.jsonl \
  --output_file out.jsonl
```

We are trying to understand how to read the output fie.

From what we understand, each question is centered around a verb, so "verbIndex" indicates that verb's location in the sentence, and all of the questions under that dictionary refer to the verb at that index. And the answer to the question is according to "span" range.
Is that a correct interpretation?

Also, is there by any chance a script that converts a QA pair to raw text?

**Comment by julianmichael** [comment]
Hi Gili,

> From what we understand, each question is centered around a verb, so "verbIndex" indicates that verb's location in the sentence, and all of the questions under that dictionary refer to the verb at that index. And the answer to the question is according to "span" range.
> Is that a correct interpretation?

Yep! That's right. I put a bit of [documentation](https://github.com/julianmichael/qasrl-modeling/commit/6dd5cdee6ea778d6ac2bc897fda40ce7dca7e42a#diff-fbdf6f68774d3b639be7bb6965fb7e09e1bcac3bd891a4d17a272d3d00ebe4ecR46) in `afirst_pipeline_sequential.py` to clarify things.

As far as printing them out in string form, I just added some code to make that easier. First I added a [couple lines](https://github.com/julianmichael/qasrl-modeling/commit/6dd5cdee6ea778d6ac2bc897fda40ce7dca7e42a#diff-fbdf6f68774d3b639be7bb6965fb7e09e1bcac3bd891a4d17a272d3d00ebe4ecR158) to the pipeline code so it remembers the verb inflections (so, you'll have to run it again to get the proper JSON output). Then, I added a sample script to print an output file at [`scripts/test/print_sample.py`](https://github.com/julianmichael/qasrl-modeling/commit/6dd5cdee6ea778d6ac2bc897fda40ce7dca7e42a#diff-2c903d3311c9fb85c2512c0b033b2a5fcfae85ed14ff876192193ef563ada1ad).

To use it, just run, e.g., `python scripts/test/print_sample.py out.jsonl`. And of course you can use that as a starting point for formatting it however you want.

Does that answer your questions?

**Comment by julianmichael** [comment]
...Oops, there was a small bug in the sample script. [Fixed now.](https://github.com/julianmichael/qasrl-modeling/commit/93a347868959ef7a70b82c92787e6c8fc9685642)

**Comment by gabrielStanovsky** [comment]
Thank you very much @julianmichael!
I've just tested it and it works perfectly :)

**Comment by julianmichael** [comment]
Great! Happy to help with any other issues that come up. I got the binary span classifier from Arie and added it; fyi in case you'd want to use that instead of having a distribution over answer spans (I'd think it should be better calibrated for thresholding span proabilities, though I haven't evaluated these particular models).
